### ISSUE TITLE
Building failed on doc.rs

### ISSUE THREAD

**Issue by Nateckert** [seppo0010/rustc-version-runtime-rs#4]
The build on doc.rs of a crate with `rustc_version_runtime`as dependency fails since the introduction of a restriction not allowing to write to the `src` directory:
https://github.com/rust-lang/docs.rs/issues/811

Writing to `CARGO_OUT_DIR` would fix the problem.

Thanks in advance !

**Comment by seppo0010** [comment]
Fixed in #5 . Thanks.
